### ISSUE TITLE
how to change SpeedDial width and height independently? 

### ISSUE THREAD

**Issue by tijnar** [darioielardi/flutter_speed_dial#155]
`SpeedDial` have the parameter `buttonSize` to change its size but I want to change its width ony when `icon` and `label` parameter is passed.

**Comment by prateekmedia** [comment]
> `SpeedDial` have the parameter `buttonSize` to change its size but I want to change its width ony when `icon` and `label` parameter is passed.

- Firstly are you on new branch
- secondly maybe what you want you will not get as by using buttonSize parameter you are setting its height only(for dial with label) and not width due to proportionality issues as SpeedDial uses FloatingActionButton under the hood.

If you still have some issue then please let me know.

**Comment by ziqq** [comment]
I have this same proble. I need change SpeedDialChild size to like so 56 the same as SpeedDial. How i can du it?

**Comment by prateekmedia** [comment]
> I have this same proble. I need change SpeedDialChild size to like so 56 the same as SpeedDial. How i can du it?

For that you need to be in the new branch, you can find link in the above comment made by me, and then set childrenButtonSize property to 56.

Also if you are on stable/master branch then you can directly set buttonSize to 56 it will only affect speedDialChild

**Comment by prateekmedia** [comment]
If you still have any issue with dev version then either describe your issue correctly or else if it is only for a specific case then use dialRoot property.
