### ISSUE TITLE
Double tap when closing prevents animation from completing

### ISSUE THREAD

**Issue by Manuito83** [darioielardi/flutter_speed_dial#166]
If ```animationSpeed``` is high enough (>~ 1000 ms) to double tap a ```speedDialChild``` or anywhere else in the overlay by mistake, the closing animation stops and the menu opens again. 

Not sure if it's intended or has any other issues I'm not aware of, but in my opinion the menu should continue closing (with taps inhibited) after a ```speedDialChild``` has been tapped once.

For clarification: the main cause for double taps is user error (probably used to a mouse?). The reason to set ```animationSpeed``` higher than the default is to allow for smoother transitions between routes once a child has been selected.

**Comment by prateekmedia** [comment]
Hi @Manuito83,

Are you on latest dev version namely 4.0.0-dev.1 ? I cannot replicate that issue here.

**Comment by prateekmedia** [comment]
It may not be possible, but I will try.

It is happening because when animation is happening then the black surface gets above the dial and we get an effect of having hole in the overlay, but due to this FAB become unclickable and we only have one way to make it happen, that is to use GestureDetector above the overlay to toogle Childrens.

If you can help making a hole using an overlay by which FAB becomes clickable and tooltips. etc will work then we can use back overlay to only Have close function instead of toggling the visibility.

**Comment by prateekmedia** [comment]
Try master branch now, it should be fixed, it will now wait for closing animation to complete before any interaction.

**Comment by Manuito83** [comment]
Thanks, this is fixed!

I guess there is still an issue with children being able to be pressed twice while the animation is closing. Not sure if I should open another issue for this.

**Comment by prateekmedia** [comment]
> closing

I didn't think this is an issue? they are button and if the animation is really slow like you say 2000 ms then I cannot disable the tapping behaviour for a particular button.

**Comment by Manuito83** [comment]
Well I guess it depends on each case, I won't open an issue for this and implement it internally.

Thanks!
