### ISSUE TITLE
Backwards compatibility (or lack of thereof)

### ISSUE THREAD

**Issue by hicnar** [darioielardi/flutter_speed_dial#180]
Folks, 

There are better ways of maintaining backwards compatibility than just removing stuff and causing the code that depends on your library to simply not compile/break. 

One could for example create an intermediate official release with both: the new way of doing things added and ready to use and the old stuff deprecated but still there. In such intermediate official release it could also be clearly announced that the marginEnd, marginBottom (and whatever else has been removed) would be removed in the following release +  some migration guidelines for those who need to migrate could be provided and retained in the description.

**Comment by prateekmedia** [comment]
Hey @hicnar,

Sorry about not notifying about that, but we were already planning to migrate to new way since May and were waiting for some testers, unfortunately no one reported any bugs related to the dev version, but it is ready to use now and comes with its own thing.

You can read the README file to learn more about it.

Regarding the marginEnd and marginBottom, they are not needed anymore cause you can just use the floatingActionButtonLocation property to specify the location of the speed dial.

If you want to know more about spacing then you can read the README or if you don't want to read it or simply didn't like the new version then you can either switch back to the old version or comment me the things that are missing or changed from your code, I will surely help you with that.

Regards,
Prateek SU

**Comment by hicnar** [comment]
@prateekmedia 

I am very happy with the new release - especially the less prominent animation when I switch to/from the view with the speed dial and I do not have any problems with migrating. As someone with over two decades of experience in the industry I'm just giving you a little hint on how to avoid issues like the one described above :)
BTW I think your plugin is truly excellent!
Keep up the good work!

Best!
K.
